"""Narrow persistence ports used by application use cases."""

from typing import Any, Callable, ContextManager, Mapping, Protocol, Sequence


class UnitOfWork(Protocol):
    def transaction(self) -> ContextManager[Any]: ...


class TaskRepository(Protocol):
    def create_task(self, name: str, input_schema: Mapping[str, Any] | None = None, description: str = "") -> Mapping[str, Any]: ...
    def task(self, task_id: str) -> Mapping[str, Any]: ...
    def definition_hash(self, task_id: str) -> str: ...
    def list_tasks(self) -> Sequence[Mapping[str, Any]]: ...
    def update_task(self, task_id: str, name: str, input_schema: Mapping[str, Any], description: str = "") -> Mapping[str, Any]: ...
    def delete_task(self, task_id: str) -> Mapping[str, Any]: ...
    def copy_task(self, task_id: str, name: str | None = None) -> Mapping[str, Any]: ...


class StepRepository(Protocol):
    def step(self, step_id: str) -> Mapping[str, Any]: ...
    def steps(self, task_id: str) -> Sequence[Mapping[str, Any]]: ...
    def save_step(self, task_id: str, document: Mapping[str, Any], step_id: str | None = None, expected_hash: str | None = None) -> Mapping[str, Any]: ...
    def reorder(self, task_id: str, step_ids: Sequence[str]) -> Sequence[Mapping[str, Any]]: ...
    def delete_step(self, step_id: str) -> Mapping[str, Any]: ...
    def confirm(self, step_id: str, attempt_id: str, expected_hash: str) -> Mapping[str, Any]: ...
    def confirm_manual(self, step_id: str, expected_hash: str, environment_id: str | None = None) -> Mapping[str, Any]: ...
    def confirm_imported(self, step_id: str, expected_hash: str) -> Mapping[str, Any]: ...


class EnvironmentRepository(Protocol):
    def save_environment(self, name: str, public_config: Mapping[str, Any], secret_refs: Mapping[str, str] | None = None, environment_id: str | None = None, descriptions: Mapping[str, str] | None = None) -> Mapping[str, Any]: ...
    def environment(self, environment_id: str | None) -> tuple[Mapping[str, Any], Mapping[str, str]]: ...
    def list_environments(self) -> Sequence[Mapping[str, Any]]: ...
    def delete_environment(self, environment_id: str) -> Mapping[str, Any]: ...


class RunRepository(Protocol):
    def create_run(self, task_id: str, inputs: Mapping[str, Any], versions: Mapping[str, str], environment_id: str | None = None, trial_step_id: str | None = None, flow_trial: bool = False, defer_inputs: bool = False, step_inputs: Mapping[str, Any] | None = None) -> Mapping[str, Any]: ...
    def run(self, run_id: str) -> Mapping[str, Any]: ...
    def run_details(self, run_id: str) -> Mapping[str, Any]: ...
    def list_runs(self, task_id: str | None = None) -> Sequence[Mapping[str, Any]]: ...
    def events(self, run_id: str) -> Sequence[Mapping[str, Any]]: ...
    def event_page(self, run_id: str, after: int = 0, limit: int = 100) -> Mapping[str, Any]: ...
    def feedback(self, attempt_id: str) -> Mapping[str, Any]: ...
    def normalize_step_inputs(self, task_id: str, step_inputs: Mapping[str, Any]) -> Mapping[str, Any]: ...
    def find_trial_command(self, command_id: str, step_id: str, inputs: Mapping[str, Any], environment_id: str | None) -> Mapping[str, Any] | None: ...
    def reset_run_results(self, run_id: str, from_step_id: str | None = None) -> None: ...
    def event(self, run_id: str, kind: str, payload: Mapping[str, Any], attempt_id: str | None = None, event_id: str | None = None) -> Any: ...
    def register_refs(self, attempt_id: str, refs: Sequence[Mapping[str, Any]]) -> Any: ...
    def finish_attempt(self, attempt_id: str, refs: Sequence[Mapping[str, Any]]) -> Any: ...
    def recover(self) -> Any: ...
    def trial_lease_for_task(self, task_id: str) -> Mapping[str, Any] | None: ...
    def trial_leases_for_task(self, task_id: str) -> Sequence[Mapping[str, Any]]: ...
    def has_unsafe_attempts(self, run_id: str) -> bool: ...
    def release_lease(self, run_id: str) -> int: ...
    def runs_for_environment(self, environment_id: str) -> Sequence[Mapping[str, Any]]: ...
    def runs_for_task(self, task_id: str) -> Sequence[Mapping[str, Any]]: ...
    def has_runtime_lease(self) -> bool: ...
    def command_receipt(self, command_id: str, run_id: str, body: Mapping[str, Any], operation: Callable[[], Mapping[str, Any]]) -> Mapping[str, Any]: ...
    def has_command_receipt(self, command_id: str) -> bool: ...
    def has_unresolved_attempts(self, run_id: str) -> bool: ...
    def has_successful_attempt(self, run_id: str, step_id: str) -> bool: ...
    def latest_attempt(self, run_id: str, step_id: str) -> Mapping[str, Any] | None: ...
    def attempts_with_status(self, run_id: str, status: str) -> Sequence[Mapping[str, Any]]: ...
    def attempt(self, attempt_id: str) -> Mapping[str, Any]: ...
    def attempt_run_id(self, attempt_id: str) -> str: ...
    def attempt_versions(self, attempt_id: str) -> Mapping[str, str]: ...
    def runtime_lease(self, run_id: str) -> Mapping[str, Any] | None: ...
    def lease_for_slot(self, slot: str) -> Mapping[str, Any] | None: ...
    def start_run(self, run_id: str, command: Mapping[str, Any], slot: str, owner_id: str, stamp: str, retry_step_ids: Sequence[str] | None = None) -> bool: ...
    def finish_run(self, run_id: str, status: str, finished_at: str | None, terminal: bool) -> None: ...
    def cancel_run(self, run_id: str, finished_at: str, succeeded: bool) -> None: ...
    def set_run_status(self, run_id: str, status: str) -> int: ...
    def clear_task_run_records(self, task_id: str) -> None: ...
    def delete_run_record(self, run_id: str) -> None: ...
    def update_attempt_reconciliation(self, attempt_id: str, status: str, effect_state: str, reconciliation_json: str, finished_at: str | None = None) -> None: ...
    def update_run_request(self, run_id: str, request_json: str) -> int: ...
    def provide_run_inputs(self, run_id: str, task_inputs_json: str | None, input_summary_json: str | None, request_json: str, event_id: str, event_json: str, created_at: str) -> None: ...
    def set_waiting_step(self, run_id: str, step_id: str, wait_until: str) -> int: ...
    def clear_waiting_step(self, run_id: str) -> int: ...
    def heartbeat(self, run_id: str, stamp: str) -> int: ...
    def create_attempt(self, attempt_id: str, task_id: str, run_id: str, step_id: str, content_hash: str, stamp: str) -> None: ...
    def set_attempt_input_summary(self, attempt_id: str, summary_json: str) -> int: ...
    def mark_attempt_cancelled(self, attempt_id: str, finished_at: str) -> int: ...
    def mark_attempt_unknown(self, attempt_id: str, error_code: str, error_phase: str | None, finished_at: str | None = None) -> int: ...
    def mark_attempt_failed(self, attempt_id: str, effect_state: str, error_code: str, error_phase: str, summary: str, finished_at: str) -> int: ...
    def private_run_request(self, run_id: str) -> Mapping[str, Any]: ...
    def private_run_inputs(self, run_id: str) -> Mapping[str, Any]: ...
    def receipt(self, attempt: Mapping[str, Any]) -> Sequence[Mapping[str, Any]] | None: ...
    def read_output(self, run_id: str, step_id: str, output: str = "data", registry: Any = None) -> Any: ...


class ResultRepository(Protocol):
    def read_output(self, run_id: str, step_id: str, output: str = "data", registry: Any = None) -> Any: ...
    def read_result(self, result_id: str, registry: Any) -> Any: ...
    def delete_result(self, result_id: str) -> Mapping[str, Any]: ...
    def receipt(self, attempt: Mapping[str, Any]) -> Sequence[Mapping[str, Any]] | None: ...
    def refs_for_attempt(self, attempt_id: str) -> Sequence[Mapping[str, Any]]: ...


class StepContextRepository(Protocol):
    def list_step_contexts(self, step_id: str) -> Sequence[Mapping[str, Any]]: ...
    def get_step_context_capture(self, context_id: str, capture_id: str, step_id: str | None = None) -> Mapping[str, Any]: ...
    def step_context_records(self, step_id: str) -> Sequence[Mapping[str, Any]]: ...
    def create_step_context_group(self, step_id: str, provider_id: str, name: str, context_notes: str = "") -> Mapping[str, Any]: ...
    def save_step_context_batch(self, step_id: str, context_id: str | None, expected_revision: int | None, provider_id: str, name: str, context_notes: str, captures: Sequence[Mapping[str, Any]]) -> Mapping[str, Any]: ...
    def update_step_context_group(self, step_id: str, context_id: str, name: str, context_notes: str = "", expected_revision: int | None = None) -> Mapping[str, Any]: ...
    def save_step_context(self, step_id: str, provider_id: str, name: str, source_page: str, item: Any, context_id: str | None = None, context_notes: str = "", request: Mapping[str, Any] | None = None, views: Sequence[Mapping[str, Any]] | None = None, include_view: bool = True, replace_capture: bool = False, captured_at: str | None = None, capture_id: str | None = None, append: bool = False, expected_revision: int | None = None, source_session_id: str | None = None) -> Mapping[str, Any]: ...
    def append_step_context_capture(self, context_id: str, capture: Mapping[str, Any], *, request: Mapping[str, Any] | None = None, include_view: bool = True, source_page: str = "draft", source_session_id: str | None = None, label: str = "", captured_at: str | None = None, expected_revision: int | None = None, step_id: str | None = None) -> Mapping[str, Any]: ...
    def replace_step_context_capture(self, context_id: str, capture_id: str, capture: Mapping[str, Any], *, request: Mapping[str, Any] | None = None, include_view: bool = True, source_page: str = "draft", source_session_id: str | None = None, label: str | None = None, captured_at: str | None = None, expected_revision: int | None = None, step_id: str | None = None) -> Mapping[str, Any]: ...
    def update_step_context_capture_label(self, context_id: str, capture_id: str, label: str, expected_revision: int | None = None, step_id: str | None = None, operation_notes: str | None = None, send_preview: bool | None = None) -> Sequence[Mapping[str, Any]]: ...
    def reorder_step_context(self, context_id: str, direction: str, expected_revision: int | None = None, step_id: str | None = None) -> Sequence[Mapping[str, Any]]: ...
    def delete_step_context_capture(self, context_id: str, capture_id: str, expected_revision: int | None = None, step_id: str | None = None) -> Mapping[str, Any]: ...
    def reorder_step_context_capture(self, context_id: str, capture_id: str, direction: str, expected_revision: int | None = None, step_id: str | None = None) -> Sequence[Mapping[str, Any]]: ...
    def delete_step_context(self, context_id: str, expected_revision: int | None = None, step_id: str | None = None) -> Mapping[str, Any]: ...


class PlanRepositoryPort(Protocol):
    def create(self, name: str = "新计划") -> Mapping[str, Any]: ...
    def copy(self, plan_id: str, expected_revision: int) -> Mapping[str, Any]: ...
    def list(self) -> Sequence[Mapping[str, Any]]: ...
    def get(self, plan_id: str) -> Mapping[str, Any]: ...
    def update(self, plan_id: str, expected_revision: int, name: str, plan_description: str = "", plan_notes: str = "", environment_id: str | None = None, plugin_ids: Sequence[str] | None = None) -> Mapping[str, Any]: ...
    def delete(self, plan_id: str, expected_revision: int) -> Mapping[str, Any]: ...


class PlanContextRepository(Protocol):
    def contexts(self, plan_id: str) -> Sequence[Mapping[str, Any]]: ...
    def get_capture(self, context_id: str, capture_id: str, plan_id: str | None = None) -> Mapping[str, Any]: ...
    def context_records(self, plan_id: str) -> Sequence[Mapping[str, Any]]: ...
    def add_context(self, plan_id: str, expected_revision: int, provider_id: str, name: str, context_notes: str, session_id: str, items: Sequence[Any], request: Mapping[str, Any] | None = None, views: Sequence[Mapping[str, Any]] | None = None, include_view: bool = True) -> Mapping[str, Any]: ...
    def update_context(self, plan_id: str, expected_revision: int, context_id: str, name: str, context_notes: str = "") -> Mapping[str, Any]: ...
    def replace_context(self, plan_id: str, expected_revision: int, context_id: str, provider_id: str, name: str, context_notes: str, session_id: str, items: Sequence[Any], request: Mapping[str, Any] | None = None, views: Sequence[Mapping[str, Any]] | None = None, include_view: bool = True) -> Mapping[str, Any]: ...
    def save_context_batch(self, plan_id: str, expected_revision: int, context_id: str | None, provider_id: str, name: str, context_notes: str, captures: Sequence[Mapping[str, Any]]) -> Mapping[str, Any]: ...
    def append_capture(self, plan_id: str, expected_revision: int, context_id: str, capture: Mapping[str, Any], *, request: Mapping[str, Any] | None = None, include_view: bool = True, session_id: str | None = None, label: str = "") -> Mapping[str, Any]: ...
    def delete_context(self, plan_id: str, expected_revision: int, context_id: str) -> Mapping[str, Any]: ...
    def reorder_context(self, plan_id: str, expected_revision: int, context_id: str, direction: str) -> Mapping[str, Any]: ...
    def replace_capture(self, plan_id: str, expected_revision: int, context_id: str, capture_id: str, capture: Mapping[str, Any], *, request: Mapping[str, Any] | None = None, include_view: bool = True, session_id: str | None = None) -> Mapping[str, Any]: ...
    def update_capture_label(self, plan_id: str, expected_revision: int, context_id: str, capture_id: str, label: str, operation_notes: str | None = None, send_preview: bool | None = None) -> Mapping[str, Any]: ...
    def delete_capture(self, plan_id: str, expected_revision: int, context_id: str, capture_id: str) -> Mapping[str, Any]: ...
    def reorder_capture(self, plan_id: str, expected_revision: int, context_id: str, capture_id: str, direction: str) -> Mapping[str, Any]: ...


class PlanGenerationRepository(Protocol):
    def create_generation(self, plan_id: str, revision: int, channel: str, request_path: str) -> Mapping[str, Any]: ...
    def generation(self, generation_id: str) -> Mapping[str, Any]: ...
    def generations(self, plan_id: str) -> Sequence[Mapping[str, Any]]: ...
    def imports(self, generation_id: str) -> Sequence[Mapping[str, Any]]: ...
    def finish_generation(self, generation_id: str, status: str, response_path: str | None = None, candidate: Mapping[str, Any] | None = None, diagnostics: Sequence[Any] | None = None) -> Mapping[str, Any]: ...
    def mark_imported(self, generation_id: str, task_id: str) -> Mapping[str, Any]: ...


class OrganizationRepository(Protocol):
    def categories(self) -> Sequence[Mapping[str, Any]]: ...
    def create_category(self, name: str) -> Mapping[str, Any]: ...
    def rename_category(self, category_id: str, name: str) -> Mapping[str, Any]: ...
    def delete_category(self, category_id: str) -> Mapping[str, Any]: ...
    def set_metadata(self, entity: str, entity_id: str, is_favorite: bool, category_id: str | None) -> Mapping[str, Any]: ...
